create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  report_no bigint generated by default as identity,
  issue text not null,
  location text not null,
  status text not null default 'In Progress',
  date_submitted timestamptz not null default now(),
  submitted_by text,
  contact_no text,
  description text not null,
  remarks text,
  map_coords jsonb,
  lat_lng_label text,
  image_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.residents (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  contact text not null,
  email text not null,
  status text not null default 'Active',
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  recipient_ids uuid[] not null default '{}',
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.reports enable row level security;
alter table public.residents enable row level security;
alter table public.notifications enable row level security;

create policy "Authenticated admins can manage reports"
on public.reports for all
to authenticated
using (true)
with check (true);

create policy "Authenticated admins can manage residents"
on public.residents for all
to authenticated
using (true)
with check (true);

create policy "Authenticated admins can manage notifications"
on public.notifications for all
to authenticated
using (true)
with check (true);

insert into storage.buckets (id, name, public)
values ('report-photos', 'report-photos', true)
on conflict (id) do nothing;

create policy "Authenticated admins can upload report photos"
on storage.objects for insert
to authenticated
with check (bucket_id = 'report-photos');

create policy "Anyone can view report photos"
on storage.objects for select
to public
using (bucket_id = 'report-photos');
